name: Pull Request Workflow

on:
  pull_request:
    # This triggers the workflow on pull request events for any branches
    branches: 
      - '*'

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: |
          echo "Pull request detected! Running custom actions..."
